name: Build server

on:
  push:
    branches-ignore:
      - gh-readonly-queue/**
  pull_request:
  merge_group:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' && !startsWith(github.ref, 'refs/tags/') }}

permissions:
  contents: read

jobs:
  build-server:
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
        - name: Linux
          os: ubuntu-latest
        - name: macOS
          os: macos-latest
        - name: Windows
          os: windows-latest
    env:
      CARGO_HTTP_MULTIPLEXING: false

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Cache Rust dependencies
      uses: Swatinem/rust-cache@v2
      with:
        cache-bin: false

    - name: Configure server
      run: >-
        cmake -S . -B build
        -DCLIENT=OFF
        -DCMAKE_COMPILE_WARNING_AS_ERROR=ON
        -DSERVER=ON
        -DTOOLS=ON
        -DDOWNLOAD_GTEST=OFF
        -DDEV=ON
        -DMYSQL=OFF
        -DWEBSOCKETS=OFF
        -DPREFER_BUNDLED_LIBS=ON
        -DCMAKE_BUILD_TYPE=Release
        -Werror=dev

    - name: Build server
      run: cmake --build build --config Release --target game-server --parallel
